### ISSUE TITLE
Juggl view crashes when reopening the vault or switching Obsidian workspaces.

### ISSUE THREAD

**Issue by FrankRuis** [HEmile/juggl#130]
First of all, love the work you have done, great plugin :)

Whenever I reopen my vault or switch to a different Obsidian workspace where I previously had a Juggl view open the Juggl pane will crash and show the following message:
![image](https://user-images.githubusercontent.com/7372399/185574609-216f00cf-06be-42a7-b467-5b9045b5484e.png)

The error is reproducible in a new empty vault with only the Juggl plugin isntalled.

I also get the following stack trace in the console when switching workspaces:
```javascript
Uncaught TypeError: Cannot read properties of undefined (reading 'on')
    at eval (plugin:juggl:15:329914)
    at t.e.tryTrigger (app.js:1:963725)
    at t.e.trigger (app.js:1:963658)
    at t.trigger (app.js:1:1520211)
    at t.activeLeafEvents (app.js:1:1510414)
    at a (app.js:1:264427)
```

And two additional stack traces on vault startup:
```javascript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'viz')
    at a.refreshNode (plugin:juggl:1:6121)
    at eval (plugin:juggl:1:6647)
    at Array.forEach (<anonymous>)
    at eval (plugin:juggl:1:6620)
    at t.e.tryTrigger (app.js:1:963725)
    at t.e.trigger (app.js:1:963658)
    at t.trigger (app.js:1:1149509)
    at t.<anonymous> (app.js:1:1146413)
    at app.js:1:235078
    at Object.next (app.js:1:235183)
```

```javascript
Uncaught TypeError: Cannot read properties of undefined (reading 'viz')
    at eval (plugin:juggl:1:7039)
    at Array.forEach (<anonymous>)
    at eval (plugin:juggl:1:7024)
    at t.e.tryTrigger (app.js:1:963725)
    at t.e.trigger (app.js:1:963658)
    at t.trigger (app.js:1:980249)
    at t.onChange (app.js:1:971450)
    at e.trigger (app.js:1:959880)
    at e.removeFile (app.js:1:960693)
    at e.<anonymous> (app.js:1:959798)
```

**Comment by Miceybeeswax** [comment]
I experience this same issue. Thanks for raising it Frank.
